### ISSUE TITLE
No PDO

### ISSUE THREAD

**Issue by gregorg** [ezweb/dblinker#26]
This lib should work without PDO.

**Comment by mathroc** [comment]
this lib works without pdo. tests are run with and without PDO (https://github.com/ezweb/dblinker/blob/master/behat.yml#L5) in fact, the master / slaves driver works with any [driver supported by dbal](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html)
for the retry driver, only mysql and postgresql driver are supported now (PDO or not)
